import Image from "next/image";

export default function Photos() {
    return (
        <div className="flex flex-wrap gap-12 justify-center">
            <Image
                className=""
                src="/DSC_2079.JPG"
                width={300}
                height={100}
                alt=""
            />
            <Image
                className=""
                src="/DSC_2079.JPG"
                width={300}
                height={100}
                alt=""
            />
            <Image
                className=""
                src="/DSC_2079.JPG"
                width={300}
                height={100}
                alt=""
            />
            <Image
                className=""
                src="/DSC_2079.JPG"
                width={300}
                height={100}
                alt=""
            />
            <Image
                className=""
                src="/DSC_2079.JPG"
                width={300}
                height={100}
                alt=""
            />
            <Image
                className=""
                src="/DSC_2079.JPG"
                width={300}
                height={100}
                alt=""
            />
            <Image
                className=""
                src="/DSC_2079.JPG"
                width={300}
                height={100}
                alt=""
            />
            <Image
                className=""
                src="/DSC_2079.JPG"
                width={300}
                height={100}
                alt=""
            />
            <Image
                className=""
                src="/DSC_2079.JPG"
                width={300}
                height={100}
                alt=""
            />
            <Image
                className=""
                src="/DSC_2079.JPG"
                width={300}
                height={100}
                alt=""
            />
            <Image
                className=""
                src="/DSC_2079.JPG"
                width={300}
                height={100}
                alt=""
            />
            <Image
                className=""
                src="/DSC_2079.JPG"
                width={300}
                height={100}
                alt=""
            />
            <Image
                className=""
                src="/DSC_2079.JPG"
                width={300}
                height={100}
                alt=""
            />
            <Image
                className=""
                src="/DSC_2079.JPG"
                width={300}
                height={100}
                alt=""
            />
        </div>
    );
}
